server:
  port: 8081
  address: b.application.com

spring:
  config:
    activate:
      on-profile: sandbox
  datasource:
    url: jdbc:h2:tcp://localhost/./student
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
