spring:
  profiles:
    active: test

  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2

  session:
    store-type: redis
    redis:
      namespace: spring:session:student
      flush-mode: on_save

server:
  servlet:
    session:
      cookie:
        name: mysessionId  # 쿠키 이름을 선택적으로 설정합니다.
        domain: .application.com  # 주요 도메인 앞에 '.'를 사용하여 서브도메인 간의 쿠키를 공유하게 합니다.
        path: /  # 쿠키의 경로. 일반적으로 루트로 설정됩니다.
        secure: false  # HTTPS를 사용하는 경우에만 쿠키를 전송하려면 이 값을 'true'로 설정
        http-only: true  # JavaScript에서 쿠키에 액세스할 수 없도록 설정합니다. 권장됩니다.



